# This is the Dockerfile for production
FROM python:3.10 AS base

ENV PATH "/opt/venv/bin:$PATH"
ENV PYTHONDONTWRITEBYTECODE True
ENV PYTHONPATH app
ENV PYTHONUNBUFFERED True

FROM base AS builder
RUN python -m venv /opt/venv
COPY requirements.txt requirements.txt
RUN pip install --upgrade pip --requirement requirements.txt
RUN python -m nltk.downloader averaged_perceptron_tagger -d /opt/venv/nltk_data

# Set the working directory to /app
FROM base
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY --from=builder /opt/venv /opt/venv
COPY . app

# Make port 80 available to the world outside this container
EXPOSE 80

